export const INPUT_CHANGE = 'inputChange'
export const ADD_TODO_ITEM = 'addTodoItem'
export const REMOVE_TODO_ITEM = 'removeTodoItem'
export const GET_LIST = 'getList'
export const INCREMENT = 'increment'
export const DECREMENT = 'decrement'
